INFO - 2024-07-25 09:36:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-07-25 09:36:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'jano'@'localhost' (using password: YES) in C:\server\htdocs\clinisoft\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\server\htdocs\clinisoft\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'jano', Object(SensitiveParameterValue), 'db_clinica', 3306, '', 0)
#1 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\server\htdocs\clinisoft\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\server\htdocs\clinisoft\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\server\htdocs\clinisoft\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 C:\server\htdocs\clinisoft\app\Controllers\AuthController.php(24): CodeIgniter\BaseModel->first()
#7 C:\server\htdocs\clinisoft\system\CodeIgniter.php(933): App\Controllers\AuthController->loginAuth()
#8 C:\server\htdocs\clinisoft\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#9 C:\server\htdocs\clinisoft\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\server\htdocs\clinisoft\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\server\htdocs\clinisoft\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\server\htdocs\clinisoft\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\server\htdocs\clinisoft\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\server\htdocs\clinisoft\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\server\htdocs\clinisoft\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\server\htdocs\clinisoft\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 C:\server\htdocs\clinisoft\app\Controllers\AuthController.php(24): CodeIgniter\BaseModel->first()
#6 C:\server\htdocs\clinisoft\system\CodeIgniter.php(933): App\Controllers\AuthController->loginAuth()
#7 C:\server\htdocs\clinisoft\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\server\htdocs\clinisoft\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\server\htdocs\clinisoft\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\server\htdocs\clinisoft\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\server\htdocs\clinisoft\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-07-25 09:36:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: loginauth]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\AuthController.php(24): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->loginAuth()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-07-25 09:36:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 09:36:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-07-25 09:36:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'jano'@'localhost' (using password: YES) in C:\server\htdocs\clinisoft\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\server\htdocs\clinisoft\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'jano', Object(SensitiveParameterValue), 'db_clinica', 3306, '', 0)
#1 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\server\htdocs\clinisoft\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\server\htdocs\clinisoft\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\server\htdocs\clinisoft\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 C:\server\htdocs\clinisoft\app\Controllers\AuthController.php(24): CodeIgniter\BaseModel->first()
#7 C:\server\htdocs\clinisoft\system\CodeIgniter.php(933): App\Controllers\AuthController->loginAuth()
#8 C:\server\htdocs\clinisoft\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#9 C:\server\htdocs\clinisoft\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\server\htdocs\clinisoft\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\server\htdocs\clinisoft\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\server\htdocs\clinisoft\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\server\htdocs\clinisoft\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\server\htdocs\clinisoft\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\server\htdocs\clinisoft\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\server\htdocs\clinisoft\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 C:\server\htdocs\clinisoft\app\Controllers\AuthController.php(24): CodeIgniter\BaseModel->first()
#6 C:\server\htdocs\clinisoft\system\CodeIgniter.php(933): App\Controllers\AuthController->loginAuth()
#7 C:\server\htdocs\clinisoft\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\server\htdocs\clinisoft\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\server\htdocs\clinisoft\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\server\htdocs\clinisoft\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\server\htdocs\clinisoft\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-07-25 09:36:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: loginauth]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\AuthController.php(24): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->loginAuth()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-07-25 09:38:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 09:38:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-07-25 09:38:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\server\htdocs\clinisoft\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\server\htdocs\clinisoft\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_clinica', 3306, '', 0)
#1 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\server\htdocs\clinisoft\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\server\htdocs\clinisoft\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\server\htdocs\clinisoft\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 C:\server\htdocs\clinisoft\app\Controllers\AuthController.php(24): CodeIgniter\BaseModel->first()
#7 C:\server\htdocs\clinisoft\system\CodeIgniter.php(933): App\Controllers\AuthController->loginAuth()
#8 C:\server\htdocs\clinisoft\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#9 C:\server\htdocs\clinisoft\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\server\htdocs\clinisoft\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\server\htdocs\clinisoft\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\server\htdocs\clinisoft\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\server\htdocs\clinisoft\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\server\htdocs\clinisoft\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\server\htdocs\clinisoft\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\server\htdocs\clinisoft\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 C:\server\htdocs\clinisoft\app\Controllers\AuthController.php(24): CodeIgniter\BaseModel->first()
#6 C:\server\htdocs\clinisoft\system\CodeIgniter.php(933): App\Controllers\AuthController->loginAuth()
#7 C:\server\htdocs\clinisoft\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\server\htdocs\clinisoft\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\server\htdocs\clinisoft\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\server\htdocs\clinisoft\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\server\htdocs\clinisoft\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-07-25 09:38:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: loginauth]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\AuthController.php(24): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->loginAuth()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-07-25 09:38:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 09:38:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 09:39:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-07-25 09:39:01 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\server\htdocs\clinisoft\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\server\htdocs\clinisoft\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_clinica', 3306, '', 0)
#1 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\server\htdocs\clinisoft\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\server\htdocs\clinisoft\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\server\htdocs\clinisoft\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 C:\server\htdocs\clinisoft\app\Controllers\AuthController.php(24): CodeIgniter\BaseModel->first()
#7 C:\server\htdocs\clinisoft\system\CodeIgniter.php(933): App\Controllers\AuthController->loginAuth()
#8 C:\server\htdocs\clinisoft\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#9 C:\server\htdocs\clinisoft\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\server\htdocs\clinisoft\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\server\htdocs\clinisoft\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\server\htdocs\clinisoft\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\server\htdocs\clinisoft\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\server\htdocs\clinisoft\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\server\htdocs\clinisoft\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\server\htdocs\clinisoft\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\server\htdocs\clinisoft\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 C:\server\htdocs\clinisoft\app\Controllers\AuthController.php(24): CodeIgniter\BaseModel->first()
#6 C:\server\htdocs\clinisoft\system\CodeIgniter.php(933): App\Controllers\AuthController->loginAuth()
#7 C:\server\htdocs\clinisoft\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#8 C:\server\htdocs\clinisoft\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\server\htdocs\clinisoft\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\server\htdocs\clinisoft\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\server\htdocs\clinisoft\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-07-25 09:39:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: loginauth]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\AuthController.php(24): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->loginAuth()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-07-25 09:40:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 09:40:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 09:40:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 09:41:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 09:41:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 10:17:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 10:21:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 10:21:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 10:22:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 10:22:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 12:06:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 12:06:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 12:06:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 13:53:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 13:53:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 13:53:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 13:54:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 13:56:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 13:59:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 14:01:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-07-25 14:01:25 --> Error: Class "App\Controllers\ResponseInterface" not found
[Method: GET, Route: recibos]
in APPPATH\Controllers\Wso2Controller.php on line 47.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Wso2Controller->fetchData()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Wso2Controller))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-07-25 14:04:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-07-25 14:04:26 --> Error: Class "App\Controllers\ResponseInterface" not found
[Method: GET, Route: recibos]
in APPPATH\Controllers\Wso2Controller.php on line 47.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Wso2Controller->fetchData()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Wso2Controller))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-07-25 14:05:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 14:09:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-07-25 14:09:15 --> Error: Class "App\Controllers\ResponseInterface" not found
[Method: GET, Route: recibos]
in APPPATH\Controllers\Wso2Controller.php on line 47.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Wso2Controller->fetchData()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Wso2Controller))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-07-25 14:11:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-25 23:11:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-07-25 23:11:49 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "plantilla.php"
[Method: GET, Route: /]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('plantilla.php')
 2 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('plantilla', [], true)
 3 APPPATH\Controllers\Home.php(10): view('plantilla')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-07-25 23:26:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
